spring:
  datasource:
    url: jdbc:mariadb://34.125.26.207:3306/small
    driver-class-name: org.mariadb.jdbc.Driver
    username: xxx
    password: xxxxxx

mybatis:
  #type-aliases-package:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true