dfmdspring:
  datasource:
    url: jdbc:db://xxx.xxx.xxx.xxx:xxxx/{}
    driver-class-name: org.mariadb.jdbc.Driver
    username: xxx
    password: xxxxxx

mybatis:
  #type-aliases-package:
  mapper-locations: classpath:mapper/*OrdersItemMapper.xml
  configuration:
    map-underscore-to-camel-case: true
